# Generated by Django 5.1.3 on 2024-12-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='status',
            new_name='status_role',
        ),
    ]
