# Generated by Django 5.1.3 on 2024-12-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='Good breakfast'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='breakfast_en',
            field=models.BooleanField(default=True, verbose_name='Good breakfast'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='breakfast_ru',
            field=models.BooleanField(default=True, verbose_name='Good breakfast'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='fitness',
            field=models.BooleanField(default=False, verbose_name='Fitness-center'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='fitness_en',
            field=models.BooleanField(default=False, verbose_name='Fitness-center'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='fitness_ru',
            field=models.BooleanField(default=False, verbose_name='Fitness-center'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='parking_en',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='parking_ru',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurant',
            field=models.BooleanField(default=True, verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurant_en',
            field=models.BooleanField(default=True, verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurant_ru',
            field=models.BooleanField(default=True, verbose_name='Restaurant'),
        ),
    ]
