# Generated by Django 5.1.3 on 2024-12-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_breakfast_hotel_breakfast_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='breakfast_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='breakfast_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='fitness_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='fitness_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='parking_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='parking_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='restaurant_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='restaurant_ru',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='Хороший завтрак'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='fitness',
            field=models.BooleanField(default=False, verbose_name='Фитнес-центр'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='restaurant',
            field=models.BooleanField(default=True, verbose_name='Ресторан'),
        ),
    ]
